### ISSUE TITLE
Polylines doesn't work due to three.js

### ISSUE THREAD

**Issue by stevenguh** [PAIR-code/scatter-gl#40]
The three version specified in the `package.json` which is `0.108` doesn't produce polylines. If I use a bundler with npm package, I will not able to produce polylines.

I setup two codepen page to show case this issue
Scatter GL 0.0.4 w/ three@0.108.0: https://codepen.io/stevenguh/pen/VwvLwve
Scatter GL 0.0.4 w/ three@0.115.0: https://codepen.io/stevenguh/pen/PoPqomK

**Comment by stevenguh** [comment]
https://github.com/PAIR-code/scatter-gl/pull/37
Maybe merging this? although there are more change than just bumping the three js version.

**Comment by cannoneyed** [comment]
Hmmm, thanks for sending this over... I've sort of neglected polylines thus far since I haven't had a reason to use them in any of the apps that I've built with Scatter-gl!

Inside Google we're tied to specific versions of all dependencies, and our latest three.js is r113 - I've verified that polylines work with r113 in your codepen so I'll try to upgrade scatter-gl to that version... Stay tuned.

**Comment by cannoneyed** [comment]
Released 0.0.5
